In [1]:
import numpy as np

numpy 계산

In [2]:
a=np.array([[1,2,3],
           [4,5,6]])

In [3]:
b=np.array([[4,5,6],
           [1,2,3]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b

array([[4, 5, 6],
       [1, 2, 3]])

In [6]:
a+b

array([[5, 7, 9],
       [5, 7, 9]])

In [7]:
a-b

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [8]:
a*b

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [9]:
a/b

array([[0.25, 0.4 , 0.5 ],
       [4.  , 2.5 , 2.  ]])

In [10]:
a//b

array([[0, 0, 0],
       [4, 2, 2]], dtype=int32)

In [11]:
a**b

array([[  1,  32, 729],
       [  4,  25, 216]], dtype=int32)

In [12]:
a|b

array([[5, 7, 7],
       [5, 7, 7]], dtype=int32)

In [15]:
a.shape

(2, 3)

In [16]:
b.shape

(2, 3)

In [13]:
np.sum(a,axis=0)

array([5, 7, 9])

In [14]:
np.sum(a,axis=1)

array([ 6, 15])

In [17]:
c=np.array([[1,2],[3,4],[5,6]])

In [18]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
c.shape

(3, 2)

In [20]:
a+c

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [22]:
a

SyntaxError: invalid syntax (3527913265.py, line 1)

In [40]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [41]:
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [42]:
a.shape, b.shape

((3, 3), (3, 2))

In [43]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [48]:
1*1 + 2*3 + 3*5

22

In [49]:
1*2 + 2*4 + 3*6

28

In [50]:
1*1 + 2*3 + 3*5

22

broadcasting

In [59]:
a=np.array([[1,2,3],[4,5,6]])

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
a+3

array([[4, 5, 6],
       [7, 8, 9]])

In [62]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [63]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [64]:
a*1

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [66]:
b=np.array([[1],[2]])

In [67]:
a.shape, b.shape

((2, 3), (2, 1))

In [68]:

a*b

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [70]:
6|3

7