In [2]:
import numpy as np

arange

In [2]:
arr=[1,2,3,4,5,6,7,8,9]

In [3]:
arr_np=np.array(arr)

In [4]:
arr_np

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr=np.arange(start=1,stop=9+1)

In [12]:
arr=np.arange(1,9+1)

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr_reverse=np.arange(stop=9+1,start=1)

In [10]:
arr_reverse

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
list(range(0,9+1,2))

[0, 2, 4, 6, 8]

In [16]:
arr2=np.arange(start=0,stop=9+1,step=2)

In [17]:
arr2

array([0, 2, 4, 6, 8])

In [18]:
arr2=np.arange(0,9+1,2)

In [19]:
arr2

array([0, 2, 4, 6, 8])

In [20]:
type(arr)

numpy.ndarray

In [21]:
r=range(1,10)

In [22]:
r

range(1, 10)

In [23]:
list(r)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
type(r)

range

In [25]:
arr_sample=np.arange(0,5,0.5)

In [26]:
arr_sample

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

정렬

In [27]:
arr=np.array([2,5,3,10,9,4,1,8,6,7])

In [28]:
arr

array([ 2,  5,  3, 10,  9,  4,  1,  8,  6,  7])

In [29]:
arr.sort()

In [30]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr.mean()

5.5

In [34]:
arr.std()

2.8722813232690143

In [38]:
arr.sum()

55

In [43]:
np.sort(arr)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [3]:
arr2d=np.array([[5,6,7,8],
               [4,3,2,1],
               [10,11,9,12]])

In [50]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10, 11, 12,  9]])

In [51]:
np.sort(arr2d,axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10, 11, 12,  9]])

In [52]:
np.sort(arr2d,axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

argsort  :  정렬된 값을 반환하지 않음, index를 반환함

In [5]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10, 11,  9, 12]])

In [4]:
np.argsort(arr2d, axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [2, 0, 1, 3]], dtype=int64)