numpy : 수학, 과학용 계산을 위해 만들어진 라이브러리

In [4]:
import numpy as np

ndarry 생성하기

In [5]:
a_list=[1,2.15,'가나다',False]

In [6]:
a_list

[1, 2.15, '가나다', False]

In [7]:
arr=np.array([1,2,3,4], dtype=int)

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [10]:
type(a_list)

list

list를 이용해 ndarray 생성하기

In [11]:
my_list1=[1,2,3,4,5]

In [13]:
arr1=np.array(my_list1)

In [14]:
arr1

array([1, 2, 3, 4, 5])

In [15]:
arr1.dtype

dtype('int32')

In [17]:
my_list2=[[1,2,3],[4,5,6]]

In [19]:
arr2=np.array(my_list2)

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr1.shape

(5,)

In [22]:
arr2.shape

(2, 3)

array는 list와 다르게 하나의 단일 데이터 타입만 허용

In [23]:
arr=np.array([1,2,3,4.15])

In [24]:
arr.dtype

dtype('float64')

In [25]:
arr

array([1.  , 2.  , 3.  , 4.15])

In [28]:
arr=np.array([1,2,3,4.65], dtype=int)

In [29]:
arr

array([1, 2, 3, 4])

In [30]:
arr=np.array([1,2,3,4.15,'가나다',False])

In [31]:
arr

array(['1', '2', '3', '4.15', '가나다', 'False'], dtype='<U32')

In [36]:
# arr=np.array([1,2,3,4.15,'가나다',False], dtype    #  error

In [34]:
arr=np.array([1,2,3,4.15,'1234'], dtype=int)

In [35]:
arr

array([   1,    2,    3,    4, 1234])

In [37]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [38]:
arr.shape

(10,)

In [39]:
list_a=[0,1,2,3,4,5,6,7,8,9]

In [40]:
print(list_a[3])

3


In [42]:
arr[-1]

9

In [45]:
arr2=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [46]:
arr2.shape

(3, 4)

In [47]:
arr2[0,1]

2

In [48]:
arr2[1,2]

7

In [51]:
arr[:3]

array([0, 1, 2])

In [52]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [50]:
arr2[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [53]:
arr2[:,3]

array([ 4,  8, 12])

In [54]:
arr=np.array([12,433,123,51,664,124,85656])

In [55]:
my_index=[1,4,5]

In [56]:
arr[my_index]

array([433, 664, 124])

In [58]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
arr2[[0,2],:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [60]:
arr2[:,[0,1,3]]

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [62]:
arr=np.array([1,2,3,4,5])

In [63]:
arr

array([1, 2, 3, 4, 5])

In [64]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
bool_list=[True,False,True]

In [66]:
arr[bool_list]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3

In [67]:
bool_list2=[True,False,True,False,True]

In [68]:
arr[bool_list2]

array([1, 3, 5])

In [69]:
bool_arr=np.array([[True,False,True,False],
                  [False,True,False,True],
                  [True,False,False,True]])

In [71]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
arr2[bool_arr]

array([ 1,  3,  6,  8,  9, 12])

In [72]:
arr2>3

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
arr2[arr2>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])